In [1]:
%matplotlib widget
import numpy as np
import pandas as pd
import random 
# import talib as ta
import math
# from numba import jit

from importlib import reload 
from qflib import basic
reload(basic)

global engine, conn
engine = basic.engine()
conn = basic.conn(engine)

df=pd.DataFrame()  # 初始化空值
vTest = 1000

In [2]:
xl_01dgree = 0.001745 # 0.1度 
xl_02dgree = 0.003490 # 0.1度 
print( str(xl_01dgree) )
# jx_xl_120>-xl_min and
sql = "SELECT ts_code, trade_date, close, pre_close, pct_change, volume, \
    diff, bar,\
    jx_days_ud60,\
    jx_xl_60, jx_xl_120, jx_xl_20, jx_xl_10, jx_xl_5,\
    sz_sum_5, sz_sum_10, sz_sum_20, \
    lj_fl_3_10, lj_fl_5_20, lj_fl_20_60, \
    sz_max_5, sz_max_10, sz_max_20 \
from day_zhibiao \
where \
    jx_days_ud60 > 20 and \
    jx_xl_60>-"+str(xl_02dgree)+" and  \
    jx_xl_10>0 and jx_xl_20>0 "
print(sql)
# and \
#     lj_fl_3_10>1 and lj_fl_5_20>1 
df = pd.read_sql_query(sql, conn)
df.shape

0.001745
SELECT ts_code, trade_date, close, pre_close, pct_change, volume,     diff, bar,    jx_days_ud60,    jx_xl_60, jx_xl_120, jx_xl_20, jx_xl_10, jx_xl_5,    sz_sum_5, sz_sum_10, sz_sum_20,     lj_fl_3_10, lj_fl_5_20, lj_fl_20_60,     sz_max_5, sz_max_10, sz_max_20 from day_zhibiao where     jx_days_ud60 > 20 and     jx_xl_60>-0.00349 and      jx_xl_10>0 and jx_xl_20>0

(12273, 23)

In [3]:
# df.head(5)
# df

,ts_code,trade_date,close,pre_close,pct_change,volume,diff,bar,jx_days_ud60,jx_xl_60,...,jx_xl_5,sz_sum_5,sz_sum_10,sz_sum_20,lj_fl_3_10,lj_fl_5_20,lj_fl_20_60,sz_max_5,sz_max_10,sz_max_20
0,002910.SZ,20230523,11.64,11.74,-0.8518,27711.2,-0.006600,0.026831,59,-0.002165,...,0.003474,-5.1537,-3.5810,-6.6901,1.118580,0.671174,1.042280,0.000000,0.00000,0.00000
1,002910.SZ,20230522,11.74,11.37,3.2542,31702.8,-0.017573,0.022565,58,-0.001666,...,0.002092,-5.9151,-2.7661,-3.1366,1.050110,0.610860,0.999337,0.000000,0.00000,0.00000
2,002910.SZ,20230515,11.62,11.61,0.0861,20891.0,-0.008205,0.060205,53,-0.001916,...,-0.001725,1.1061,-4.8090,-0.3024,0.795249,0.667692,0.940932,1.032700,1.03270,1.03270
3,002910.SZ,20230512,11.61,11.77,-1.3594,22306.0,-0.015607,0.067854,52,-0.002192,...,-0.000344,-2.0620,-4.2729,-2.2481,0.702501,0.697970,0.917012,0.086133,1.11972,1.11972
4,002910.SZ,20230511,11.77,11.52,2.1701,29901.1,-0.023810,0.076615,51,-0.001658,...,0.001893,-3.8631,-4.9174,-2.6451,0.699232,0.753891,0.892482,0.000000,0.00000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12268,300761.SZ,20200102,59.91,59.40,0.8586,26361.4,-0.618879,0.523574,39,-0.003173,...,0.010089,-0.0354,-1.9123,-25.2236,1.491770,1.307770,0.794775,2.320150,2.32015,2.32015
12269,300761.SZ,20191230,58.89,57.39,2.6137,32337.9,-1.021880,0.363811,37,-0.002209,...,0.008569,4.1040,0.3664,-27.8802,1.334800,1.063300,0.746684,4.092380,4.09238,4.09238
12270,300761.SZ,20190726,56.40,56.16,0.4274,27161.3,-0.424015,0.482555,51,-0.000088,...,0.006225,12.8580,20.0055,14.7715,1.142470,0.787925,0.851187,14.858200,29.66310,29.66310
12271,300761.SZ,20190725,56.16,54.56,2.9326,38628.5,-0.643686,0.383523,50,-0.002001,...,0.007112,14.7982,27.2153,15.8764,0.955497,0.743922,0.819739,15.349000,30.21720,30.21720
12272,300761.SZ,20190708,57.60,56.85,1.3193,42431.2,-0.871864,0.548467,37,-0.002585,...,0.009116,-9.3326,-8.3158,14.5078,1.212390,1.228090,0.552314,0.000000,0.00000,14.01040

In [4]:
# df[['pct_change', 'diff', 'bar']].head(5)

   pct_change      diff       bar
0     -0.8518 -0.006600  0.026831
1      3.2542 -0.017573  0.022565
2      0.0861 -0.008205  0.060205
3     -1.3594 -0.015607  0.067854
4      2.1701 -0.023810  0.076615

In [10]:
#筛选a列中值为a的行，形成新的df1
# df1 = df[ df['a'].isin(['a']) ]
df.shape, df[ df['sz_max_20'] > 30 ]

((12273, 23),
          ts_code trade_date  close  pre_close  pct_change   volume      diff  \
 7      002910.SZ   20221115  10.77      10.72      0.4664  23768.0  0.035763
 8      002910.SZ   20221114  10.72      10.55      1.6114  29162.7  0.009176
 79     002910.SZ   20180321  18.66      18.40      1.4100  72001.1 -0.308619
 80     002910.SZ   20180319  18.57      17.35      7.0300  66004.6 -0.391108
 81     002910.SZ   20180314  18.82      18.67      0.8000  52004.1 -0.295661
 ...          ...        ...    ...        ...         ...      ...       ...
 12210  300755.SZ   20210401  23.49      23.10      1.6883  11514.9 -0.115700
 12211  300755.SZ   20210330  23.32      23.24      0.3442  11060.8 -0.204412
 12212  300755.SZ   20210329  23.24      22.55      3.0599  22586.3 -0.263649
 12213  300755.SZ   20210316  22.96      22.56      1.7730  10876.4 -0.416303
 12271  300761.SZ   20190725  56.16      54.56      2.9326  38628.5 -0.643686

             bar  jx_days_ud60  jx_xl_60  ...   jx_xl_5  sz_sum_5  sz_sum_10  \
 7      0.096645            38 -0.000293  ...  0.005651   -0.8578     1.3232
 8      0.094219            37 -0.000170  ...  0.004357    1.2676    -1.0406
 79     0.126439            31  0.000264  ... -0.001771   14.2000    28.6400
 80     0.102532            29  0.000331  ... -0.009695   19.2400    19.3900
 81     0.281752            26  0.001099  ...  0.003136   -0.3000    13.9000
 ...         ...           ...       ...  ...       ...       ...        ...
 12210  0.133798            69 -0.001925  ...  0.010804   16.7402    32.4993
 12211  0.105967            67 -0.002409  ...  0.004038   14.6150    28.5182
 12212  0.073222            66 -0.002279  ...  0.003613   13.1410    15.1923
 12213  0.105021            57 -0.003256  ... -0.007461   -0.4008     1.6666
 12271  0.383523            50 -0.002001  ...  0.007112   14.7982    27.2153

        sz_sum_20  lj_fl_3_10  lj_fl_5_20  lj_fl_20_60  sz_max_5  sz_max_10  \
 7        42.0063    1.165920    0.996340     0.643882   3.15692    3.15692
 8        32.4932    1.202590    1.002650     0.641391   3.63806    3.63806
 79       12.5900    0.997026    1.003610     0.583288  26.36660   30.76100
 80       20.6100    0.889446    1.047570     0.546146  20.40930   26.97900
 81       24.4600    0.996002    1.271490     0.523146   0.00000   25.29220
 ...          ...         ...         ...          ...       ...        ...
 12210    47.9578    0.932424    0.888332     0.613435  17.92250   36.44100
 12211    40.6523    1.297120    0.910231     0.590222  15.26590   31.21780
 12212    40.1478    1.230610    0.856857     0.579115  13.59720   19.19100
 12213    30.1848    0.666174    0.742083     0.557874   1.52439    1.56794
 12271    15.8764    0.955497    0.743922     0.819739  15.34900   30.21720

        sz_max_20
 7        49.3965
 8        36.4739
 79       33.1190
 80       33.7641
 81       31.9872
 ...          ...
 12210    58.7484
 12211    47.7702
 12212    47.0310
 12213    33.2753
 12271    30.2172

 [416 rows x 23 columns])