# 数据处理
- 数据获取
    tushare   ：['open','high','low','close','pre_close','vol',    'change', 'pct_chg',    'amount']
    mplfinance：['open','high','low','close','pre_close','volume', 'change', 'pct_change', 'value']
- 输入读取: 
    用pro_bar函数，qfq选项必须；
- 索引
    sort_index(ascending=True)
- 字段选择
    df=df['', '', '']
- 字段更名
    df.columns=['A','B','C']
## S2, DB结构

    第一个字段为日期，没有字段名 
    open: 当日开盘价 
    high, 当日最高价
     low, 当日最低价 
    close, 当日收盘价 
    volume, 交易量（手） 
    MA5, 收盘价的5日移动平均线 
    MA10, 收盘价的10日移动平均线 
    MA20, 收盘价的20日移动平均线 
    MA60, 收盘价的60日移动平均线 
    change, 当日收盘价相对上个收盘价的变化值 
    pct_change, 当日收盘价相对上个收盘价的涨跌幅百分比 
    value, 交易额（亿元） 
    upper_lim, 涨停价格 
    lower_lim, 跌停价格 

    last_close, 昨日收盘价 
    average, 平均价 
    volrate, 交易量（手） 

    dema, DEMA指标值 
    macd-m, MACD指标-M线， macd 
    macd-s, MACD指标-S线， singal
    macd-h, MACD指标-红绿柱, history
    rsi, RSI指标 
    bb-u, 布林带线上轨 
    bb-m, 布林带线中轨
    bb-l, 布林带线下轨
 

## macd
- diff, macd-m, macd = 12 天 EMA - 26 天 EMA
- dea,  macd-s, signal = 9 天 MACD的EMA
- bar,  macd-h, hist = MACD - MACD signal

## 更多库研究

- PyqtGraph ： 可以动态优化

In [6]:
%matplotlib widget
import numpy as np
import pandas as pd
import random 
import matplotlib.pyplot as plt
import mplfinance as mpf
import talib as ta

import tushare as ts
ts.set_token('11137efdbeac800606d677871a55b3fd5aef79890c59867a8f34d03e')
pro = ts.pro_api()

from numba import jit
df=pd.DataFrame()

In [7]:
# 计算macd
# 输入df_name,算法参数。其中ewm函数算法快300-500倍
def cal_macd(dfIn=df, macd_way=2, ema_fast=12, ema_slow=26, dea_day=9):
    dfIn['ema_fast'] = dfIn['close'].ewm(span=ema_fast,     adjust=False).mean()
    dfIn['ema_slow'] = dfIn['close'].ewm(span=ema_slow,     adjust=False).mean()
    dfIn['diff'] = dfIn['ema_fast'] - dfIn['ema_slow']
    dfIn['dea'] = dfIn['diff'].ewm(span=9, adjust=False).mean()
    dfIn['bar'] = (dfIn['diff'] - dfIn['dea']) * 2
    return dfIn

@jit(nopython=True)
def jit_cal_macd(dfIn=df, macd_way=2, ema_fast=12, ema_slow=26, dea_day=9):
    dfIn['ema_fast'] = dfIn['close'].ewm(span=ema_fast,     adjust=False).mean()
    dfIn['ema_slow'] = dfIn['close'].ewm(span=ema_slow,     adjust=False).mean()
    dfIn['diff'] = dfIn['ema_fast'] - dfIn['ema_slow']
    dfIn['dea'] = dfIn['diff'].ewm(span=9, adjust=False).mean()
    dfIn['bar'] = (dfIn['diff'] - dfIn['dea']) * 2
    return dfIn

# 计算MA
def cal_ma_v0():
    df['MA5']  = df['close'].rolling(5).mean()
    df['MA10'] = df['close'].rolling(10).mean()
    df['MA20'] = df['close'].rolling(20).mean()
    df['MA30'] = df['close'].rolling(30).mean()
    df['MA48'] = df['close'].rolling(48).mean()
    
def cal_ma_v1(dfIn=df):
    dfIn['MA5'] = dfIn['close'].rolling(5).mean()
    dfIn['MA10'] = dfIn['close'].rolling(10).mean()
    dfIn['MA20'] = dfIn['close'].rolling(20).mean()
    dfIn['MA30'] = dfIn['close'].rolling(30).mean()
    dfIn['MA48'] = dfIn['close'].rolling(48).mean()
    return dfIn

@jit(nopython=True)
def jit_cal_ma(dfIn=df):
    df['MA5'] = df['close'].rolling(5).mean()
    df['MA10'] = df['close'].rolling(10).mean()
    df['MA20'] = df['close'].rolling(20).mean()
    df['MA30'] = df['close'].rolling(30).mean()
    df['MA48'] = df['close'].rolling(48).mean()
    # return df.dropna()
    # dfIn['MA5'] = dfIn['close'].rolling(5).mean()
    # dfIn['MA10'] = dfIn['close'].rolling(10).mean()
    # dfIn['MA20'] = dfIn['close'].rolling(20).mean()
    # dfIn['MA30'] = dfIn['close'].rolling(30).mean()
    # dfIn['MA48'] = dfIn['close'].rolling(48).mean()
    # # df['MA60'] = np.nan
    # # df['MA60'] = df['close'].rolling(60).mean()
    # return dfIn.dropna()

In [8]:
# test
# df = pd.read_csv('tushare/000001.SZ.ts.csv', index_col='trade_date',
#                  parse_dates=True).sort_index(ascending=True)
# # df = df.sort_index(ascending=True)
# df.rename(columns={'vol': 'volume', 'pct_chg': 'pct_change',
#           'amount': 'value'}, inplace=True)
# close = df.close.values
# df

In [9]:
%%time

# ts_list = pd.read_csv( 'data/stock_list_first.csv')
ts_list = pd.read_csv( 'data/stock_list_first.csv')
for i in range( ts_list.shape[0]  ):
    if ts_list['ts_code'][i].startswith('8'):
        break
    else:
        print('计算：', ts_list['ts_code'][i] )
    
    ts_file = 'tushare/' + ts_list['ts_code'][i] +'.ts.csv'
    df = pd.read_csv( ts_file, index_col='trade_date', parse_dates=True).sort_index(ascending=True)
    # df = df.sort_index(ascending=True)
    df.rename( columns={'vol':'volume','pct_chg':'pct_change', 'amount':'value'}, inplace=True  )
 
    # 计算MACD
    # way1 : charlie's coding
    # df['ema_fast']=0.0
    # df['ema_slow']=0.0
    # df['diff']=0.0
    # df['dea']=0.0
    # df['bar']=0.0
    # df = cal_macd(df, 2, 12, 26, 9)
    # way2 : ta-lib
    close = df.close.values  # 为 MACD 数据初始化close
    df['diff'], df['dea'], df['bar'] = ta.MACD(close, fastperiod=12, slowperiod=26, signalperiod=9)
    
    # 计算MA
    # way1: my coding
    # df['MA5'] = np.nan
    # df['MA10'] = np.nan
    # df['MA20'] = np.nan
    # df['MA30'] = np.nan
    # df['MA48'] = np.nan
    # df = cal_ma_v1(df)
    # way 2: ta-lib
    df.insert( df.shape[1], 'MA5', ta.MA(df['close'], 5) )
    df.insert( df.shape[1], 'MA10', ta.MA(df['close'], 10) )
    df.insert( df.shape[1], 'MA20', ta.MA(df['close'], 20) )
    df.insert( df.shape[1], 'MA30', ta.MA(df['close'], 30) )
    df.insert( df.shape[1], 'MA48', ta.MA(df['close'], 48) )
    df.insert( df.shape[1], 'MA60', ta.MA(df['close'], 60) )
    df.insert( df.shape[1], 'MA125', ta.MA(df['close'], 125) )
    
    # 计算BOLL, 
    df['bb-u'], df['bb-m'], df['bb-l'] = ta.BBANDS( close,timeperiod=20,nbdevup=2,nbdevdn=2,matype=0 )
    # df['upper'], df['middle'], df['lower'] = ta.BBANDS( close,timeperiod=20,nbdevup=2,nbdevdn=2,matype=0 )
    # 空值填充为0
    df = df.fillna(value=0)

    # 输出 csv
    ts_cal_file = 'cal/' + ts_list['ts_code'][i] +'.cal.csv'
    df.to_csv(ts_cal_file)
df
    

# df['upper'], df['middle'], df['lower'] = ta.BBANDS( df.close.values,timeperiod=20,nbdevup=2,nbdevdn=2,matype=0 )
# MA60  = ta.MA(df['close'], 60)
# MA120 = ta.MA(df['close'], 120)

# 插入和删除行，很有用

# df.insert( df.shape[1], 'MA250', ta.MA(df['close'], 250) )
# df.drop( labels=['MA125'], axis=1, inplace=True)

计算： 601318.SH
计算： 002475.SZ
计算： 600352.SH
计算： 600143.SH
计算： 600031.SH
CPU times: user 227 ms, sys: 17.1 ms, total: 244 ms
Wall time: 263 ms

,Unnamed: 0,ts_code,open,high,low,close,pre_close,change,pct_change,volume,...,MA5,MA10,MA20,MA30,MA48,MA60,MA125,upper,middle,lower
trade_date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,2915,600031.SH,6.5189,6.5349,6.3967,6.4498,6.5207,-0.0709,-1.0873,61694.26,...,0.00000,0.000,0.0000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000
2010-01-05,2914,600031.SH,6.4481,6.4994,6.3418,6.4552,6.4498,0.0054,0.0837,75582.38,...,0.00000,0.000,0.0000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000
2010-01-06,2913,600031.SH,6.4552,6.8555,6.4020,6.6323,6.4552,0.1771,2.7435,128889.43,...,0.00000,0.000,0.0000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000
2010-01-07,2912,600031.SH,6.6323,6.7722,6.4924,6.5668,6.6323,-0.0655,-0.9876,141505.04,...,0.00000,0.000,0.0000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000
2010-01-08,2911,600031.SH,6.5668,6.5668,6.3418,6.4481,6.5668,-0.1187,-1.8076,76754.82,...,6.51044,0.000,0.0000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-13,4,600031.SH,24.4200,24.6100,23.8700,23.9200,24.4900,-0.5700,-2.3275,1053381.19,...,24.52000,23.827,23.6490,23.563000,23.062500,23.164000,25.25872,24.848782,23.6490,22.449218
2022-01-14,3,600031.SH,23.8800,23.8800,23.3300,23.3800,23.9200,-0.5400,-2.2575,950402.58,...,24.23400,23.851,23.6235,23.597000,23.075417,23.144333,25.23632,24.823388,23.6235,22.423612
2022-01-17,2,600031.SH,23.3100,23.5000,23.0900,23.4200,23.3800,0.0400,0.1711,762110.29,...,23.94600,23.913,23.6175,23.629333,23.101042,23.115333,25.22096,24.820195,23.6175,22.414805
2022-01-18,1,600031.SH,23.2600,23.8000,23.0800,23.5400,23.4200,0.1200,0.5124,1182797.99,...,23.75000,23.987,23.6370,23.657667,23.137708,23.093167,25.20480,24.821248,23.6370,22.452752
2022-01-19,0,600031.SH,23.7700,24.5000,23.6800,24.3500,23.5400,0.8100,3.4410,1967515.21,...,23.72200,24.114,23.6830,23.661000,23.175000,23.088000,25.19928,24.902461,23.6830,22.463539