# 数据处理
- 数据获取
    tushare   ：['open','high','low','close','pre_close','vol',    'change', 'pct_chg',    'amount']
    mplfinance：['open','high','low','close','pre_close','volume', 'change', 'pct_change', 'value']
- 输入读取: 
    用pro_bar函数，qfq选项必须；
- 索引
    sort_index(ascending=True)
- 字段选择
    df=df['', '', '']
- 字段更名
    df.columns=['A','B','C']


**[test examples](https://github.com/matplotlib/mplfinance/blob/master/examples/)**

In [155]:
%matplotlib widget
import numpy as np
import numba as jit
import pandas as pd
import random 
import matplotlib.pyplot as plt
import mplfinance as mpf

import tushare as ts
ts.set_token('11137efdbeac800606d677871a55b3fd5aef79890c59867a8f34d03e')
pro = ts.pro_api()

ts_code = '601318.SH'
# ts_code = '002475.SZ'
# ts_code = 'JD'
ts_file = ts_code+'.csv'
ts_all_file = ts_code+'.all.csv'
temp_file = 'temp.csv'

In [156]:
%%time
# 国内股市：可显示复权后和复权前信息
dfcn = ts.pro_bar(ts_code=ts_code, asset='E', adj='qfq', start_date='20000101', end_date='20211231')
# df02.info()
dfcn.to_csv( temp_file )
dfcn

CPU times: user 108 ms, sys: 7.49 ms, total: 116 ms
Wall time: 1.53 s

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,601318.SH,20211231,50.4300,50.8500,50.1500,50.4100,50.4100,0.0000,0.0000,358000.24,1805071.299
1,601318.SH,20211230,50.9000,50.9900,50.4100,50.4100,50.8100,-0.4000,-0.7872,427879.89,2167180.060
2,601318.SH,20211229,51.1000,51.1600,50.5200,50.8100,50.8700,-0.0600,-0.1179,376469.06,1913669.685
3,601318.SH,20211228,50.3000,51.1300,50.1000,50.8700,49.9800,0.8900,1.7807,617358.56,3137430.544
4,601318.SH,20211227,49.9600,50.2000,49.8700,49.9800,49.8200,0.1600,0.3212,274701.06,1373481.524
...,...,...,...,...,...,...,...,...,...,...,...
3542,601318.SH,20070307,17.6914,18.3203,17.5430,18.1562,17.6758,0.4804,2.7178,287463.78,1317764.044
3543,601318.SH,20070306,17.1875,17.9688,17.0898,17.6758,17.3359,0.3399,1.9607,297727.88,1337719.318
3544,601318.SH,20070305,17.9609,18.0352,17.0039,17.3359,18.1289,-0.7930,-4.3742,419196.74,1880502.808
3545,601318.SH,20070302,18.3594,18.5312,17.9219,18.1289,18.2773,-0.1484,-0.8119,425048.32,1981445.189
3546,601318.SH,20070301,19.5312,19.9102,17.8906,18.2773,13.2031,5.0742,38.4319,1977633.51,9500302.911

In [140]:
# 美股数据, 每天只有5次
# ts_code = 'JD'
# ts_file = ts_code+'.csv'
# ts_all_file = ts_code+'.all.csv'

# df_us = pro.us_daily(ts_code=ts_code, start_date='20190101', end_date='20190904')
# df_us
# df_us.to_csv( ts_file )

In [141]:
# 读取上证指数
# df_sh = ts.pro_bar(ts_code='000001.SH', asset='I', start_date='20100101', end_date='20211231')
# df_sh

In [157]:
# read from csv, add volume column, set index 
df = pd.read_csv( temp_file, index_col='trade_date', parse_dates=True)
# 选择字段、设置 acending 顺序
df = df[['open','high','low','close','pre_close','vol', 'change', 'pct_chg', 'amount']].sort_index(ascending=True)
# 字段更名： vol, pct_chg, amount to volume, pct_change, value
df.columns=['open','high','low','close','pre_close','volume', 'change', 'pct_change', 'value']
df

,open,high,low,close,pre_close,volume,change,pct_change,value
trade_date,,,,,,,,,
2007-03-01,19.5312,19.9102,17.8906,18.2773,13.2031,1977633.51,5.0742,38.4319,9500302.911
2007-03-02,18.3594,18.5312,17.9219,18.1289,18.2773,425048.32,-0.1484,-0.8119,1981445.189
2007-03-05,17.9609,18.0352,17.0039,17.3359,18.1289,419196.74,-0.7930,-4.3742,1880502.808
2007-03-06,17.1875,17.9688,17.0898,17.6758,17.3359,297727.88,0.3399,1.9607,1337719.318
2007-03-07,17.6914,18.3203,17.5430,18.1562,17.6758,287463.78,0.4804,2.7178,1317764.044
...,...,...,...,...,...,...,...,...,...
2021-12-27,49.9600,50.2000,49.8700,49.9800,49.8200,274701.06,0.1600,0.3212,1373481.524
2021-12-28,50.3000,51.1300,50.1000,50.8700,49.9800,617358.56,0.8900,1.7807,3137430.544
2021-12-29,51.1000,51.1600,50.5200,50.8100,50.8700,376469.06,-0.0600,-0.1179,1913669.685
2021-12-30,50.9000,50.9900,50.4100,50.4100,50.8100,427879.89,-0.4000,-0.7872,2167180.060
2021-12-31,50.4300,50.8500,50.1500,50.4100,50.4100,358000.24,0.0000,0.0000,1805071.299

In [158]:
df

,open,high,low,close,pre_close,volume,change,pct_change,value
trade_date,,,,,,,,,
2007-03-01,19.5312,19.9102,17.8906,18.2773,13.2031,1977633.51,5.0742,38.4319,9500302.911
2007-03-02,18.3594,18.5312,17.9219,18.1289,18.2773,425048.32,-0.1484,-0.8119,1981445.189
2007-03-05,17.9609,18.0352,17.0039,17.3359,18.1289,419196.74,-0.7930,-4.3742,1880502.808
2007-03-06,17.1875,17.9688,17.0898,17.6758,17.3359,297727.88,0.3399,1.9607,1337719.318
2007-03-07,17.6914,18.3203,17.5430,18.1562,17.6758,287463.78,0.4804,2.7178,1317764.044
...,...,...,...,...,...,...,...,...,...
2021-12-27,49.9600,50.2000,49.8700,49.9800,49.8200,274701.06,0.1600,0.3212,1373481.524
2021-12-28,50.3000,51.1300,50.1000,50.8700,49.9800,617358.56,0.8900,1.7807,3137430.544
2021-12-29,51.1000,51.1600,50.5200,50.8100,50.8700,376469.06,-0.0600,-0.1179,1913669.685
2021-12-30,50.9000,50.9900,50.4100,50.4100,50.8100,427879.89,-0.4000,-0.7872,2167180.060
2021-12-31,50.4300,50.8500,50.1500,50.4100,50.4100,358000.24,0.0000,0.0000,1805071.299

In [168]:
# 计算macd
# 输入df nama， 以及macd算法，算法2快1000倍
def cal_macd(dfIn=df,macd_way=2):
    # dfIn = dfIn.copy()
    ema_fast = 12
    ema_slow = 26
    dea_day = 9

    dfIn['ema12']=0.0
    dfIn['ema26']=0.0
    dfIn['diff']=0.0
    dfIn['dea']=0.0
    dfIn['bar']=0.0

    # 算法 1 - charlie， 手工计算
    if macd_way == 1:
        # test
        # print('way -1')
        ema12_rate1 = (ema_fast-1)/(ema_fast+1)
        ema12_rate2 = 1 - ema12_rate1
        ema26_rate1 = (ema_slow-1)/(ema_slow+1)
        ema26_rate2 = 1 - ema26_rate1
        dea_rate1 = (dea_day-1)/(dea_day+1)
        dea_rate2 = 1 - dea_rate1
        dfIn['ema12'][0] = dfIn['close'][0]
        dfIn['ema26'][0] = dfIn['close'][0]
        for i in range(1, dfIn.shape[0]):
            dfIn['ema12'][i] = dfIn['ema12'][i-1] * \
                ema12_rate1 + dfIn['close'][i]*ema12_rate2
            dfIn['ema26'][i] = dfIn['ema26'][i-1] * \
                ema26_rate1 + dfIn['close'][i]*ema26_rate2
            dfIn['diff'][i] = dfIn['ema12'][i] - dfIn['ema26'][i]

            dfIn['dea'][i] = dfIn['dea'][i-1]*dea_rate1 + dfIn['diff'][i]*dea_rate2
            dfIn['bar'][i] = - (dfIn['dea'][i] - dfIn['diff'][i]) * 2
#     # 算法 2 - ExMA算法 -charlie
    elif macd_way == 2:
        dfIn['ema12'] = dfIn['close'].ewm(span=12,     adjust=False).mean()
        dfIn['ema26'] = dfIn['close'].ewm(span=26,     adjust=False).mean()
        dfIn['diff'] = dfIn['ema12'] - dfIn['ema26']
        dfIn['dea'] = dfIn['diff'].ewm(span=9, adjust=False).mean()
        dfIn['bar'] = (dfIn['diff'] - dfIn['dea']) * 2

In [173]:
%%time
# df = df.copy()
df['ema12']=0.0
df['ema26']=0.0
df['diff']=0.0
df['dea']=0.0
df['bar']=0.0
cal_macd(df, 2)
df

CPU times: user 6.1 ms, sys: 2.78 ms, total: 8.88 ms
Wall time: 6.37 ms

,open,high,low,close,pre_close,volume,change,pct_change,value,MA5,MA10,MA20,MA30,MA48,ema12,ema26,diff,dea,bar
trade_date,,,,,,,,,,,,,,,,,,,
2007-03-01,19.5312,19.9102,17.8906,18.2773,13.2031,1977633.51,5.0742,38.4319,9500302.911,NaN,NaN,NaN,NaN,NaN,18.277300,18.277300,0.000000,0.000000,0.000000
2007-03-02,18.3594,18.5312,17.9219,18.1289,18.2773,425048.32,-0.1484,-0.8119,1981445.189,NaN,NaN,NaN,NaN,NaN,18.254469,18.266307,-0.011838,-0.002368,-0.018941
2007-03-05,17.9609,18.0352,17.0039,17.3359,18.1289,419196.74,-0.7930,-4.3742,1880502.808,NaN,NaN,NaN,NaN,NaN,18.113151,18.197388,-0.084237,-0.018742,-0.130992
2007-03-06,17.1875,17.9688,17.0898,17.6758,17.3359,297727.88,0.3399,1.9607,1337719.318,NaN,NaN,NaN,NaN,NaN,18.045866,18.158752,-0.112886,-0.037570,-0.150631
2007-03-07,17.6914,18.3203,17.5430,18.1562,17.6758,287463.78,0.4804,2.7178,1317764.044,17.91482,NaN,NaN,NaN,NaN,18.062841,18.158563,-0.095723,-0.049201,-0.093043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,49.9600,50.2000,49.8700,49.9800,49.8200,274701.06,0.1600,0.3212,1373481.524,50.20800,50.461,50.1565,49.962333,50.312317,50.279300,50.214793,0.064507,0.128593,-0.128173
2021-12-28,50.3000,51.1300,50.1000,50.8700,49.9800,617358.56,0.8900,1.7807,3137430.544,50.21400,50.463,50.2890,49.979333,50.259385,50.370177,50.263327,0.106850,0.124245,-0.034789
2021-12-29,51.1000,51.1600,50.5200,50.8100,50.8700,376469.06,-0.0600,-0.1179,1913669.685,50.34000,50.474,50.3860,50.004667,50.205000,50.437842,50.303821,0.134021,0.126200,0.015642
2021-12-30,50.9000,50.9900,50.4100,50.4100,50.8100,427879.89,-0.4000,-0.7872,2167180.060,50.37800,50.395,50.4625,50.034667,50.146667,50.433558,50.311686,0.121872,0.125334,-0.006924
2021-12-31,50.4300,50.8500,50.1500,50.4100,50.4100,358000.24,0.0000,0.0000,1805071.299,50.49600,50.382,50.5335,50.049667,50.110000,50.429934,50.318969,0.110965,0.122461,-0.022990

In [174]:
# 计算MA

def cal_ma(dfIn=df):
    dfIn['MA5'] = dfIn['close'].rolling(5).mean()
    dfIn['MA10'] = dfIn['close'].rolling(10).mean()
    dfIn['MA20'] = dfIn['close'].rolling(20).mean()
    dfIn['MA30'] = dfIn['close'].rolling(30).mean()
    dfIn['MA48'] = dfIn['close'].rolling(48).mean()
    # df['MA60'] = np.nan
    # df['MA60'] = df['close'].rolling(60).mean()

In [175]:
%%time
# df = df.copy
df['MA5'] = np.nan
df['MA10'] = np.nan
df['MA20'] = np.nan
df['MA30'] = np.nan
df['MA48'] = np.nan
cal_ma(df)
df

CPU times: user 6.12 ms, sys: 2.58 ms, total: 8.69 ms
Wall time: 6.33 ms

,open,high,low,close,pre_close,volume,change,pct_change,value,MA5,MA10,MA20,MA30,MA48,ema12,ema26,diff,dea,bar
trade_date,,,,,,,,,,,,,,,,,,,
2007-03-01,19.5312,19.9102,17.8906,18.2773,13.2031,1977633.51,5.0742,38.4319,9500302.911,NaN,NaN,NaN,NaN,NaN,18.277300,18.277300,0.000000,0.000000,0.000000
2007-03-02,18.3594,18.5312,17.9219,18.1289,18.2773,425048.32,-0.1484,-0.8119,1981445.189,NaN,NaN,NaN,NaN,NaN,18.254469,18.266307,-0.011838,-0.002368,-0.018941
2007-03-05,17.9609,18.0352,17.0039,17.3359,18.1289,419196.74,-0.7930,-4.3742,1880502.808,NaN,NaN,NaN,NaN,NaN,18.113151,18.197388,-0.084237,-0.018742,-0.130992
2007-03-06,17.1875,17.9688,17.0898,17.6758,17.3359,297727.88,0.3399,1.9607,1337719.318,NaN,NaN,NaN,NaN,NaN,18.045866,18.158752,-0.112886,-0.037570,-0.150631
2007-03-07,17.6914,18.3203,17.5430,18.1562,17.6758,287463.78,0.4804,2.7178,1317764.044,17.91482,NaN,NaN,NaN,NaN,18.062841,18.158563,-0.095723,-0.049201,-0.093043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,49.9600,50.2000,49.8700,49.9800,49.8200,274701.06,0.1600,0.3212,1373481.524,50.20800,50.461,50.1565,49.962333,50.312317,50.279300,50.214793,0.064507,0.128593,-0.128173
2021-12-28,50.3000,51.1300,50.1000,50.8700,49.9800,617358.56,0.8900,1.7807,3137430.544,50.21400,50.463,50.2890,49.979333,50.259385,50.370177,50.263327,0.106850,0.124245,-0.034789
2021-12-29,51.1000,51.1600,50.5200,50.8100,50.8700,376469.06,-0.0600,-0.1179,1913669.685,50.34000,50.474,50.3860,50.004667,50.205000,50.437842,50.303821,0.134021,0.126200,0.015642
2021-12-30,50.9000,50.9900,50.4100,50.4100,50.8100,427879.89,-0.4000,-0.7872,2167180.060,50.37800,50.395,50.4625,50.034667,50.146667,50.433558,50.311686,0.121872,0.125334,-0.006924
2021-12-31,50.4300,50.8500,50.1500,50.4100,50.4100,358000.24,0.0000,0.0000,1805071.299,50.49600,50.382,50.5335,50.049667,50.110000,50.429934,50.318969,0.110965,0.122461,-0.022990

In [176]:
# 删除带有na的行
df = df.dropna()   
df.to_csv( ts_all_file )
df

,open,high,low,close,pre_close,volume,change,pct_change,value,MA5,MA10,MA20,MA30,MA48,ema12,ema26,diff,dea,bar
trade_date,,,,,,,,,,,,,,,,,,,
2007-05-15,25.1562,25.1914,24.0039,24.0352,25.0039,111533.98,-0.9687,-3.8742,698693.032,24.88674,24.56799,22.97951,21.644933,20.190844,24.018469,22.546576,1.471894,1.434836,0.074114
2007-05-16,24.0234,24.6016,23.7109,24.3477,24.0352,98841.50,0.3125,1.3002,610776.702,24.62190,24.78753,23.15119,21.850013,20.317310,24.069120,22.679992,1.389128,1.425695,-0.073134
2007-05-17,24.3477,24.9141,24.2188,24.5508,24.3477,84327.98,0.2031,0.8342,528182.974,24.49456,24.95706,23.33498,22.051187,20.451100,24.143225,22.818571,1.324654,1.405487,-0.161665
2007-05-18,24.4102,24.5469,23.8320,24.2969,24.5508,111772.95,-0.2539,-1.0342,695617.734,24.44690,24.90237,23.47502,22.248453,20.596121,24.166867,22.928077,1.238790,1.372147,-0.266714
2007-05-21,23.7930,25.2305,23.7500,24.7891,24.2969,168888.72,0.4922,2.0258,1073946.037,24.40394,24.80901,23.61252,22.444680,20.744315,24.262595,23.065930,1.196665,1.337051,-0.280772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,49.9600,50.2000,49.8700,49.9800,49.8200,274701.06,0.1600,0.3212,1373481.524,50.20800,50.46100,50.15650,49.962333,50.312317,50.279300,50.214793,0.064507,0.128593,-0.128173
2021-12-28,50.3000,51.1300,50.1000,50.8700,49.9800,617358.56,0.8900,1.7807,3137430.544,50.21400,50.46300,50.28900,49.979333,50.259385,50.370177,50.263327,0.106850,0.124245,-0.034789
2021-12-29,51.1000,51.1600,50.5200,50.8100,50.8700,376469.06,-0.0600,-0.1179,1913669.685,50.34000,50.47400,50.38600,50.004667,50.205000,50.437842,50.303821,0.134021,0.126200,0.015642
2021-12-30,50.9000,50.9900,50.4100,50.4100,50.8100,427879.89,-0.4000,-0.7872,2167180.060,50.37800,50.39500,50.46250,50.034667,50.146667,50.433558,50.311686,0.121872,0.125334,-0.006924
2021-12-31,50.4300,50.8500,50.1500,50.4100,50.4100,358000.24,0.0000,0.0000,1805071.299,50.49600,50.38200,50.53350,50.049667,50.110000,50.429934,50.318969,0.110965,0.122461,-0.022990

In [ ]:
my_color = mpf.make_marketcolors(up='r',
                                 down='g',
                                 edge='inherit',
                                 wick='inherit',
                                 volume='inherit')
my_style = mpf.make_mpf_style(marketcolors=my_color,
                                  figcolor='(0.82, 0.83, 0.85)',
                                  gridcolor='(0.82, 0.83, 0.85)')
title_font = {'fontname': 'pingfang HK',
              'size':     '16',
              'color':    'black',
              'weight':   'bold',
              'va':       'bottom',
              'ha':       'center'}
large_red_font = {'fontname': 'Arial',
                  'size':     '24',
                  'color':    'red',
                  'weight':   'bold',
                  'va':       'bottom'}
large_green_font = {'fontname': 'Arial',
                    'size':     '24',
                    'color':    'green',
                    'weight':   'bold',
                    'va':       'bottom'}
small_red_font = {'fontname': 'Arial',
                  'size':     '12',
                  'color':    'red',
                  'weight':   'bold',
                  'va':       'bottom'}
small_green_font = {'fontname': 'Arial',
                    'size':     '12',
                    'color':    'green',
                    'weight':   'bold',
                    'va':       'bottom'}
normal_label_font = {'fontname': 'pingfang HK',
                     'size':     '12',
                     'color':    'black',
                     'weight':   'normal',
                     'va':       'bottom',
                     'ha':       'right'}
normal_font = {'fontname': 'Arial',
               'size':     '12',
               'color':    'black',
               'weight':   'normal',
               'va':       'bottom',
               'ha':       'left'}

In [ ]:
class InterCandle:
    def __init__(self, data, my_style):
        self.pressed = False
        self.xpress = None

        # 初始化交互式K线图对象，历史数据作为唯一的参数用于初始化对象
        self.data = data
        self.style = my_style
        # 设置初始化的K线图显示区间起点为0，即显示第0到第99个交易日的数据（前100个数据）
        self.idx_start = 0
        self.idx_range = 100
        # 设置ax1图表中显示的均线类型
        self.avg_type = 'ma'
        self.indicator = 'macd'
        
        # 初始化figure对象，在figure上建立三个Axes对象并分别设置好它们的位置和基本属性
        self.fig = mpf.figure(style=my_style, figsize=(12, 8), facecolor=(0.82, 0.83, 0.85))
        fig = self.fig
        self.ax1 = fig.add_axes([0.08, 0.25, 0.88, 0.60])
        self.ax2 = fig.add_axes([0.08, 0.15, 0.88, 0.10], sharex=self.ax1)
        self.ax2.set_ylabel('volume')
        self.ax3 = fig.add_axes([0.08, 0.05, 0.88, 0.10], sharex=self.ax1)
        self.ax3.set_ylabel('macd')
        # 初始化figure对象，在figure上预先放置文本并设置格式，文本内容根据需要显示的数据实时更新
        self.t1 = fig.text(0.50, 0.94, ts_code, **title_font)
        self.t2 = fig.text(0.12, 0.90, '开/收: ', **normal_label_font)
        self.t3 = fig.text(0.14, 0.89, f'', **large_red_font)
        self.t4 = fig.text(0.14, 0.86, f'', **small_red_font)
        self.t5 = fig.text(0.22, 0.86, f'', **small_red_font)
        self.t6 = fig.text(0.12, 0.86, f'', **normal_label_font)
        self.t7 = fig.text(0.40, 0.90, '高: ', **normal_label_font)
        self.t8 = fig.text(0.40, 0.90, f'', **small_red_font)
        self.t9 = fig.text(0.40, 0.86, '低: ', **normal_label_font)
        self.t10 = fig.text(0.40, 0.86, f'', **small_green_font)
        self.t11 = fig.text(0.55, 0.90, '量(万手): ', **normal_label_font)
        self.t12 = fig.text(0.55, 0.90, f'', **normal_font)
        self.t13 = fig.text(0.55, 0.86, '额(亿元): ', **normal_label_font)
        self.t14 = fig.text(0.55, 0.86, f'', **normal_font)
        self.t15 = fig.text(0.70, 0.90, '涨停: ', **normal_label_font)
        self.t16 = fig.text(0.70, 0.90, f'', **small_red_font)
        self.t17 = fig.text(0.70, 0.86, '跌停: ', **normal_label_font)
        self.t18 = fig.text(0.70, 0.86, f'', **small_green_font)
        self.t19 = fig.text(0.85, 0.90, '均价: ', **normal_label_font)
        self.t20 = fig.text(0.85, 0.90, f'', **normal_font)
        self.t21 = fig.text(0.85, 0.86, '昨收: ', **normal_label_font)
        self.t22 = fig.text(0.85, 0.86, f'', **normal_font)

        fig.canvas.mpl_connect('button_press_event', self.on_press)
        fig.canvas.mpl_connect('button_release_event', self.on_release)
        fig.canvas.mpl_connect('motion_notify_event', self.on_motion)
        # fig.canvas.mpl_connect('scroll_event', self.on_scroll)


    def refresh_plot(self, idx_start, idx_range):
        """ 根据最新的参数，重新绘制整个图表
        """
        all_data = self.data
        plot_data = all_data.iloc[idx_start: idx_start + idx_range]

        ap = []
        # 添加K线图重叠均线，根据均线类型添加移动均线或布林带线
        if self.avg_type == 'ma':
            ap.append(mpf.make_addplot(plot_data[['MA5', 'MA10', 'MA20', 'MA48']], ax=self.ax1))
        elif self.avg_type == 'bb':
            ap.append(mpf.make_addplot(plot_data[['bb-u', 'bb-m', 'bb-l']], ax=self.ax1))
        # 添加指标，根据指标类型添加MACD或RSI或DEMA
        if self.indicator == 'macd':
            ap.append(mpf.make_addplot(plot_data[['diff', 'dea']], ylabel='macd', ax=self.ax3))
            bar_r = np.where(plot_data['bar'] > 0, plot_data['bar'], 0)
            bar_g = np.where(plot_data['bar'] <= 0, plot_data['bar'], 0)
            ap.append(mpf.make_addplot(bar_r, type='bar', color='red', ax=self.ax3))
            ap.append(mpf.make_addplot(bar_g, type='bar', color='green', ax=self.ax3))
            
#             ap.append(mpf.make_addplot(plot_data[['macd-m', 'macd-s']], ylabel='macd', ax=self.ax3))
#             bar_r = np.where(plot_data['macd-h'] > 0, plot_data['macd-h'], 0)
#             bar_g = np.where(plot_data['macd-h'] <= 0, plot_data['macd-h'], 0)
#             ap.append(mpf.make_addplot(bar_r, type='bar', color='red', ax=self.ax3))
#             ap.append(mpf.make_addplot(bar_g, type='bar', color='green', ax=self.ax3))
            
            # df['macd-m']=df['diff']
            # df['macd-s']=df['dea']
            # df['macd-h']=df['bar']    
            
        # elif self.indicator == 'rsi':
        #     ap.append(mpf.make_addplot([75] * len(plot_data), color=(0.75, 0.6, 0.6), ax=self.ax3))
        #     ap.append(mpf.make_addplot([30] * len(plot_data), color=(0.6, 0.75, 0.6), ax=self.ax3))
        #     ap.append(mpf.make_addplot(plot_data['rsi'], ylabel='rsi', ax=self.ax3))
        # else:  # indicator == 'dema'
        #     ap.append(mpf.make_addplot(plot_data['dema'], ylabel='dema', ax=self.ax3))
        # 绘制图表
        mpf.plot(plot_data,
                 ax=self.ax1,
                 volume=self.ax2,
                 addplot=ap,
                 type='candle',
                 style=self.style,
                 datetime_format='%Y-%m',
                 xrotation=0)
                 # figratio=(16, 9), figscale=1.2)
        # self.fig.show()

    def refresh_texts(self, display_data):
        """ 更新K线图上的价格文本
        """
        # display_data是一个交易日内的所有数据，将这些数据分别填入figure对象上的文本中
        self.t3.set_text(f'{np.round(display_data["open"], 3)} / {np.round(display_data["close"], 3)}')
        self.t4.set_text(f'{np.round(display_data["change"], 3)}')
        self.t5.set_text(f'[{np.round(display_data["pct_change"], 3)}%]')
        self.t6.set_text(f'{display_data.name.date()}')
        self.t8.set_text(f'{np.round(display_data["high"], 3)}')
        self.t10.set_text(f'{np.round(display_data["low"], 3)}')
        self.t12.set_text(f'{np.round(display_data["volume"] / 10000, 3)}')
        self.t14.set_text(f'{display_data["value"]}')
        # self.t16.set_text(f'{np.round(display_data["upper_lim"], 3)}')
        # self.t18.set_text(f'{np.round(display_data["lower_lim"], 3)}')
        # self.t20.set_text(f'{np.round(display_data["average"], 3)}')
        # self.t22.set_text(f'{np.round(display_data["last_close"], 3)}')
        # 根据本交易日的价格变动值确定开盘价、收盘价的显示颜色
        if display_data['change'] > 0:  # 如果今日变动额大于0，即今天价格高于昨天，今天价格显示为红色
            close_number_color = 'red'
        elif display_data['change'] < 0:  # 如果今日变动额小于0，即今天价格低于昨天，今天价格显示为绿色
            close_number_color = 'green'
        else:
            close_number_color = 'black'
        self.t3.set_color(close_number_color)
        self.t4.set_color(close_number_color)
        self.t5.set_color(close_number_color)

    def on_press(self, event):
        if not event.inaxes == self.ax1:
            return
        if event.button != 1:
            return
        self.pressed = True
        self.xpress = event.xdata

        # 切换当前ma类型, 在ma、bb、none之间循环
        if event.inaxes == self.ax1 and event.dblclick == 1:
            if self.avg_type == 'ma':
                self.avg_type = 'bb'
            elif self.avg_type == 'bb':
                self.avg_type = 'none'
            else:
                self.avg_type = 'ma'
        # 切换当前indicator类型，在macd/dma/rsi/kdj之间循环
        if event.inaxes == self.ax3 and event.dblclick == 1:
            # if self.indicator == 'macd':
            #     self.indicator = 'dma'
            # elif self.indicator == 'dma':
            #     self.indicator = 'rsi'
            # elif self.indicator == 'rsi':   
            #     self.indicator = 'kdj'
            # else:
            #     self.indicator = 'macd'
            self.indicator = 'macd'
            
        self.ax1.clear()
        self.ax2.clear()
        self.ax3.clear()
        self.refresh_plot(self.idx_start, self.idx_range)

    def on_release(self, event):
        self.pressed = False
        dx = int(event.xdata - self.xpress)
        self.idx_start -= dx
        if self.idx_start <= 0:
            self.idx_start = 0
        if self.idx_start >= len(self.data) - 100:
            self.idx_start = len(self.data) - 100

    def on_motion(self, event):
        if not self.pressed:
            return
        if not event.inaxes == self.ax1:
            return
        dx = int(event.xdata - self.xpress)
        new_start = self.idx_start - dx
        # 设定平移的左右界限，如果平移后超出界限，则不再平移
        if new_start <= 0:
            new_start = 0
        if new_start >= len(self.data) - 100:
            new_start = len(self.data) - 100
        self.ax1.clear()
        self.ax2.clear()
        self.ax3.clear()

        self.refresh_texts(self.data.iloc[new_start])
        self.refresh_plot(new_start, self.idx_range)

		# def on_scroll(self, event):
		# # 仅当鼠标滚轮在axes1范围内滚动时起作用
		# if event.inaxes != self.ax1:
		# return
		# if event.button == 'down':
		# # 缩小20%显示范围
		# scale_factor = 0.8
		# if event.button == 'up':
		# # 放大20%显示范围
		# scale_factor = 1.2
		# # 设置K线的显示范围大小
		# self.idx_range = int(self.idx_range * scale_factor)
		# # 限定可以显示的K线图的范围，最少不能少于30个交易日，最大不能超过当前位置与
		# # K线数据总长度的差
		# data_length = len(self.data)
		# if self.idx_range >= data_length - self.idx_start:
		# self.idx_range = data_length - self.idx_start
		# if self.idx_range <= 30:
		# self.idx_range = 30 
		# # 更新图表（注意因为多了一个参数idx_range，refresh_plot函数也有所改动）
		# self.ax1.clear()
		# self.ax2.clear()
		# self.ax3.clear()
		# self.refresh_texts(self.data.iloc[self.idx_start])
		# self.refresh_plot(self.idx_start, self.idx_range)

In [ ]:

if __name__ == '__main__':
    candle = InterCandle(df, my_style)
    candle.idx_start = len(df)-100
    candle.idx_range = 100
    candle.refresh_texts(df.iloc[ candle.idx_range + 1 ])
    candle.refresh_plot(candle.idx_start, candle.idx_range)