# 数据处理
- 数据获取
    tushare   ：['open','high','low','close','pre_close','vol',    'change', 'pct_chg',    'amount']
    mplfinance：['open','high','low','close','pre_close','volume', 'change', 'pct_change', 'value']
- 输入读取: 
    用pro_bar函数，qfq选项必须；
- 索引
    sort_index(ascending=True)
- 字段选择
    df=df['', '', '']
- 字段更名
    df.columns=['A','B','C']
## S2, DB结构

    第一个字段为日期，没有字段名 
    open: 当日开盘价 
    high, 当日最高价
     low, 当日最低价 
    close, 当日收盘价 
    volume, 交易量（手） 
    MA5, 收盘价的5日移动平均线 
    MA10, 收盘价的10日移动平均线 
    MA20, 收盘价的20日移动平均线 
    MA60, 收盘价的60日移动平均线 
    change, 当日收盘价相对上个收盘价的变化值 
    pct_change, 当日收盘价相对上个收盘价的涨跌幅百分比 
    value, 交易额（亿元） 
    upper_lim, 涨停价格 
    lower_lim, 跌停价格 

    last_close, 昨日收盘价 
    average, 平均价 
    volrate, 交易量（手） 

    dema, DEMA指标值 
    macd-m, MACD指标-M线， macd 
    macd-s, MACD指标-S线， singal
    macd-h, MACD指标-红绿柱, history
    rsi, RSI指标 
    bb-u, 布林带线上轨 
    bb-m, 布林带线中轨
    bb-l, 布林带线下轨
 

## macd
- diff, macd-m, macd = 12 天 EMA - 26 天 EMA
- dea,  macd-s, signal = 9 天 MACD的EMA
- bar,  macd-h, hist = MACD - MACD signal

## 更多库研究

- PyqtGraph ： 可以动态优化
- blitting:

In [1]:
%matplotlib widget
import numpy as np
import pandas as pd
import random 
import matplotlib.pyplot as plt
import mplfinance as mpf
import talib as ta

import tushare as ts
ts.set_token('11137efdbeac800606d677871a55b3fd5aef79890c59867a8f34d03e')
pro = ts.pro_api()

# from numba import jit
df=pd.DataFrame()
vTest = 1000

In [2]:
# 计算macd
# 输入df_name,算法参数。其中ewm函数算法快300-500倍
def cal_macd(dfIn=df, macd_way=2, ema_fast=12, ema_slow=26, dea_day=9):

    dfIn['ema_fast'] = dfIn['close'].ewm(span=ema_fast,     adjust=False).mean()
    dfIn['ema_slow'] = dfIn['close'].ewm(span=ema_slow,     adjust=False).mean()
    dfIn['diff'] = dfIn['ema_fast'] - dfIn['ema_slow']
    dfIn['dea'] = dfIn['diff'].ewm(span=9, adjust=False).mean()
    dfIn['bar'] = (dfIn['diff'] - dfIn['dea']) * 2

    return dfIn

# @jit(nopython=True)
# def jit_cal_macd(dfIn=df, macd_way=2, ema_fast=12, ema_slow=26, dea_day=9):
#     dfIn['ema_fast'] = dfIn['close'].ewm(span=ema_fast,     adjust=False).mean()
#     dfIn['ema_slow'] = dfIn['close'].ewm(span=ema_slow,     adjust=False).mean()
#     dfIn['diff'] = dfIn['ema_fast'] - dfIn['ema_slow']
#     dfIn['dea'] = dfIn['diff'].ewm(span=9, adjust=False).mean()
#     dfIn['bar'] = (dfIn['diff'] - dfIn['dea']) * 2
#     return dfIn

# 计算MA
def cal_ma_v0():
    df['MA5']  = df['close'].rolling(5).mean()
    df['MA10'] = df['close'].rolling(10).mean()
    df['MA20'] = df['close'].rolling(20).mean()
    df['MA30'] = df['close'].rolling(30).mean()
    df['MA48'] = df['close'].rolling(48).mean()
    
def cal_ma_v1(dfIn=df):
    dfIn['MA5'] = dfIn['close'].rolling(5).mean()
    dfIn['MA10'] = dfIn['close'].rolling(10).mean()
    dfIn['MA20'] = dfIn['close'].rolling(20).mean()
    dfIn['MA30'] = dfIn['close'].rolling(30).mean()
    dfIn['MA48'] = dfIn['close'].rolling(48).mean()
    return dfIn

In [3]:
# ts_list = pd.read_csv( 'data/stock_list_first.csv')
# ts_list = pd.read_csv( 'data/stock_list_first.csv')
ts_list = pd.read_csv( 'data/stock_list.csv')
print( ts_list )
print('行数:'+ str( ts_list.shape[0] ), '; 列数：', ts_list.shape[1])

# ts_list.index[1]

     Unnamed: 0    ts_code  symbol  name area industry market exchange  \
0             0  300001.SZ  300001   特锐德   山东     电气设备    创业板     SZSE
1             1  300002.SZ  300002  神州泰岳   北京     软件服务    创业板     SZSE
2             2  300003.SZ  300003  乐普医疗   北京     医疗保健    创业板     SZSE
3             3  300006.SZ  300006  莱美药业   重庆     化学制药    创业板     SZSE
4             4  300007.SZ  300007  汉威科技   河南     电器仪表    创业板     SZSE
..          ...        ...     ...   ...  ...      ...    ...      ...
286         286  300973.SZ  300973  立高食品   广东       食品    创业板     SZSE
287         287  300979.SZ  300979  华利集团   广东       服饰    创业板     SZSE
288         288  300981.SZ  300981  中红医疗   河北     医疗保健    创业板     SZSE
289         289  300999.SZ  300999   金龙鱼   上海       食品    创业板     SZSE
290         290  301039.SZ  301039  中集车辆   深圳     汽车整车    创业板     SZSE

    list_status  list_date is_hs
0             L   20091030     S
1             L   20091030     S
2             L   20091030     S
3             L   20091030     S
4             L   20091030     S
..          ...        ...   ...
286           L   20210415     S
287           L   20210426     S
288           L   20210427     S
289           L   20201015     S
290           L   20210708     S

[291 rows x 11 columns]
行数:291 ; 列数： 11

In [4]:
%%time

for i in range( ts_list.shape[0]  ):
    # ？？， 不计算8字头，北京股票
    # print(df.index[i], df['ts_code'][i])
    if ts_list['ts_code'][i].startswith('8'):
        # break
        continue
    # else:
        # print('计算：', ts_list['ts_code'][i] )
    
    ts_file = 'tushare/' + ts_list['ts_code'][i] +'.ts.csv'
    df = pd.read_csv( ts_file, index_col='trade_date', parse_dates=True).sort_index(ascending=True)
    # print(df.head(3))
        
    # df['pct_upper'] = (df['high'] - max( df['open'], df['close']) ) / df['pre_close']
    # df['pct_down'] = (df['close'] - min( df['open'], df['close']) ) / df['pre_close']
    # pct_upper: 上引线百分比
    # pct_change: 涨幅百分比， from pct_chg
    # pct_down: 下引线百分比

    # df = df.sort_index(ascending=True)
    # df.rename( columns={'vol':'volume','pct_chg':'pct_change', 'amount':'value'}, inplace=True  )
 
    # 计算MACD
    # way1 : charlie's coding
    # df['ema_fast']=0.0
    # df['ema_slow']=0.0
    # df['diff']=0.0
    # df['dea']=0.0
    # df['bar']=0.0
    # df = cal_macd(df, 2, 12, 26, 9)
    # way2 : ta-lib
    close = df.close.values  # 为 MACD 数据初始化close
    df['diff'], df['dea'], df['bar'] = ta.MACD(close, fastperiod=12, slowperiod=26, signalperiod=9)
    
    # 计算MA
    # way1: my coding
    # df['MA5'] = np.nan
    # df['MA10'] = np.nan
    # df['MA20'] = np.nan
    # df['MA30'] = np.nan
    # df['MA48'] = np.nan
    # df = cal_ma_v1(df)
    # way 2: ta-lib
    df.insert( df.shape[1], 'MA3_pct_change', ta.MA(df['pct_change'], 3) )
    df.insert( df.shape[1], 'MA5_pct_change', ta.MA(df['pct_change'], 5) )
    df.insert( df.shape[1], 'MA10_pct_change', ta.MA(df['pct_change'], 10) )
    df.insert( df.shape[1], 'MA5', ta.MA(df['close'], 5) )
    df.insert( df.shape[1], 'MA10', ta.MA(df['close'], 10) )
    df.insert( df.shape[1], 'MA15', ta.MA(df['close'], 15) )
    df.insert( df.shape[1], 'MA20', ta.MA(df['close'], 20) )
    df.insert( df.shape[1], 'MA30', ta.MA(df['close'], 30) )
    df.insert( df.shape[1], 'MA48', ta.MA(df['close'], 48) )
    df.insert( df.shape[1], 'MA60', ta.MA(df['close'], 60) )
    df.insert( df.shape[1], 'MA125', ta.MA(df['close'], 125) )
    
    # 计算BOLL, 
    df['bb-u'], df['bb-m'], df['bb-l'] = ta.BBANDS( close,timeperiod=20,nbdevup=2,nbdevdn=2,matype=0 )
    # df['upper'], df['middle'], df['lower'] = ta.BBANDS( close,timeperiod=20,nbdevup=2,nbdevdn=2,matype=0 )
    # 空值填充为0
    df = df.fillna(value=0)

    # 输出 csv
    ts_cal_file = 'cal/' + ts_list['ts_code'][i] +'.cal.csv'
    df.to_csv(ts_cal_file)
df
    

# df['upper'], df['middle'], df['lower'] = ta.BBANDS( df.close.values,timeperiod=20,nbdevup=2,nbdevdn=2,matype=0 )
# MA60  = ta.MA(df['close'], 60)
# MA120 = ta.MA(df['close'], 120)

# 插入和删除行，很有用

# df.insert( df.shape[1], 'MA250', ta.MA(df['close'], 250) )
# df.drop( labels=['MA125'], axis=1, inplace=True)

CPU times: user 8.29 s, sys: 600 ms, total: 8.89 s
Wall time: 8.88 s

,Unnamed: 0,ts_code,open,high,low,close,pre_close,change,pct_change,volume,...,MA10,MA15,MA20,MA30,MA48,MA60,MA125,bb-u,bb-m,bb-l
trade_date,,,,,,,,,,,,,,,,,,,,,
2021-07-08,172,301039.SZ,20.4280,20.4280,15.2140,15.4961,6.7704,8.7257,128.8801,1199860.22,...,0.000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
2021-07-09,171,301039.SZ,14.2023,14.9125,13.3658,13.4728,15.4961,-2.0233,-13.0568,808432.12,...,0.000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
2021-07-12,170,301039.SZ,13.2977,14.3288,13.1615,13.5700,13.4728,0.0972,0.7215,605081.08,...,0.000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
2021-07-13,169,301039.SZ,13.3171,13.3171,12.8113,12.9475,13.5700,-0.6225,-4.5873,468677.66,...,0.000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
2021-07-14,168,301039.SZ,13.0545,13.5603,12.9377,13.2004,12.9475,0.2529,1.9533,420068.02,...,0.000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-18,4,301039.SZ,9.5800,9.7400,9.5500,9.7100,9.5900,0.1200,1.2513,43368.00,...,9.791,10.150667,10.3605,10.589333,11.066875,11.477000,11.570040,11.624580,10.3605,9.096420
2022-03-21,3,301039.SZ,9.7100,10.1100,9.6700,10.0000,9.7100,0.2900,2.9866,77188.07,...,9.745,10.094000,10.3040,10.554000,11.014583,11.420000,11.552530,11.525759,10.3040,9.082241
2022-03-22,2,301039.SZ,9.9800,10.0200,9.7400,9.9200,10.0000,-0.0800,-0.8000,40372.78,...,9.727,10.026667,10.2535,10.513667,10.961458,11.359500,11.536248,11.450835,10.2535,9.056165
2022-03-23,1,301039.SZ,9.9800,10.0500,9.9100,9.9300,9.9200,0.0100,0.1008,41184.70,...,9.739,9.960667,10.1895,10.468667,10.914583,11.297167,11.516622,11.309848,10.1895,9.069152
2022-03-24,0,301039.SZ,9.9000,9.9500,9.7600,9.8400,9.9300,-0.0900,-0.9063,37113.46,...,9.723,9.890667,10.1415,10.425000,10.863333,11.241000,11.498610,11.235050,10.1415,9.047950